---
abstract: 'Provides an opinionated method for verifying permissions on a per-action basis by inspecting the user.'
author:
  - 'J. Shirley <jshirley@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Test: 0
  FindBin: 0
  HTTP::Request::Common: 0
  Moose: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Controller-Role-PermissionCheck
requires:
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Runtime: 0
  Message::Stack: 0
  Moose::Role: 0
  Try::Tiny: 0
resources:
  repository: https://github.com/jshirley/catalystx-controller-role-permissioncheck
version: 0.02
